CREATE DATABASE IF NOT EXISTS COP4331;

USE COP4331;

CREATE TABLE IF NOT EXISTS Users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Login VARCHAR(50) UNIQUE,
    Password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Contacts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Email VARCHAR(100),
    Phone VARCHAR(20),
    UserID INT,
    FOREIGN KEY (UserID) REFERENCES Users(ID)
);
