name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Navigate to web directory
          cd /var/www/html
          
          # Pull latest changes
          git pull origin main || git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git .
          
          # Install/update PHP dependencies if you use Composer
          if [ -f composer.json ]; then
            composer install --no-dev --optimize-autoloader
          fi
          
          # Set proper permissions
          sudo chown -R www-data:www-data /var/www/html
          sudo chmod -R 755 /var/www/html
          
          # Restart Apache (optional, only if needed)
          sudo systemctl reload apache2
